stages:
- name: publish
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: demandcluster/api-docs:1.0.1
      pushRemote: true
      registry: harbor.demandcluster.com
timeout: 60
notification: {}
